---
version: "3"

services:

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address :9001
    ports:
    - 9001:9001
    - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: devops123
    volumes:
    - minio:/data

  mongo:
    image: mongo:8.0.10@sha256:15fb53a5160ebabff5ecade8f8b5d48721b68ea190957a7f35b5b38e8340e62b
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devops123
    volumes:
    - mongo:/data/db

volumes:
  mongo:
  minio:
