---
version: '3'
services:
  db:
    image: mysql:9.3@sha256:072f96c2f1ebb13f712fd88d0ef98f2ef9a52ad4163ae67b550ed6720b6d642e
    volumes:
      - db_data:/var/lib/mysql
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: openvpn
volumes:
  db_data: {}
