---
version: "3"

services:

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address :9001
    ports:
    - 9001:9001
    - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: devops123
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
    - minio:/data

  mongo:
    image: mongo:8.0.10@sha256:15fb53a5160ebabff5ecade8f8b5d48721b68ea190957a7f35b5b38e8340e62b
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devops123
    volumes:
    - mongo:/data/db

  mongo-exporter:
    image: percona/mongodb_exporter:0.44.0@sha256:d9c577166068197bf6908296d9742cc8267e7b7e1054199436d6d922e8921679
    ports:
    - 9216:9216
    command: --mongodb.uri=mongodb://root:devops123@mongo:27017/ --collect-all

  prometheus:
    image: prom/prometheus:v3.4.1@sha256:9abc6cf6aea7710d163dbb28d8eeb7dc5baef01e38fa4cd146a406dd9f07f70d
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  mongo:
  minio:
