FROM python:3.13.3-alpine3.20

RUN apk --no-cache add curl

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY * .

CMD ["flask", "--app=app", "run", "--host=0.0.0.0", "--port=8080"]
